#!/bin/sh
file=/tmp/$$
date=`date +"%Y%m%d"`


mkdir history/ipv6/$date


cp dns6 history/ipv6/$date
cp mx6 history/ipv6/$date
cp www6 history/ipv6/$date

cp errdns6 history/ipv6/$date
cp errmx6 history/ipv6/$date
cp errwww6 history/ipv6/$date

cp truedns6 history/ipv6/$date
cp truemx6 history/ipv6/$date
cp truewww6 history/ipv6/$date


./ipv6 > $file
cat $file > ../public_html/nipv6/index.html
rm $file



