#!/bin/sh
ping -c 1 8.8.8.8
if [ "$?" != "0" ] ; then
	exit
fi




sh ipv6 | tee resultat

cat /dev/null > $1
for i in `cat resultat` ; do
	ipv6=`echo $i | cut -d , -f 1`
	dnssec=`echo $i | cut -d , -f 2`
	domain=`echo $i | cut -d , -f 3`
        if [ "$ipv6" = "yes" ] ; then
                echo "<img width=18 height=16 src=/thumbsup.gif> &nbsp; " >> $1
        fi
        if [ "$ipv6" = "no" ] ; then
                echo "<img width=18 height=16 src=/nothumb.gif>  &nbsp;" >> $1
        fi
        if [ "$dnssec" = "yes" ] ; then
                echo "<img width=18 height=16 src=/dnssec.jpg>  &nbsp;" >> $1
        fi
        if [ "$dnssec" = "no" ] ; then
                echo "<img width=18 height=16 src=/nothumb.gif>  &nbsp;" >> $1
        fi
	if [ "$ipv6" = "yes" ] ; then
		if [ "$dnssec" = "yes" ] ; then 
			echo "<span style=\"color:green\"> $domain</span><br>" >>$1
			echo yes!
		fi
	fi
        if [ "$ipv6" = "no" ] ; then
                if [ "$dnssec" = yes ] ; then 
                        echo "<span style=\"color:blue\"> $domain</span><br>" >>$1
                fi
        fi
       if [ "$ipv6" = "yes" ] ; then
                if [ "$dnssec" = "no" ] ; then
                        echo "<span style=\"color:blue\"> $domain</span><br>" >>$1
                fi
        fi
       if [ "$ipv6" = "no" ] ; then
                if [ "$dnssec" = "no" ] ; then
                        echo "<span style=\"color:red\"> $domain</span><br>" >>$1
                fi
        fi

	
unset ipv6
unset dnssec

done
echo "Updated `date`<br><br>">../public_html/digirad/index.html

cat $1 >>../public_html/digirad/index.html

