#!/bin/sh


cp secured secured.org

./dnssec2 |tee resultat.txt
php file.php < resultat.txt >../../public_html/ddns/index2.html
cp ../../public_html/ddns/index2.html ../../public_html/ddns/index.html

cat resultat.txt | awk -F , '{ print $1","$2}'|grep yes > secured
