#!/bin/sh

date=`date +"%Y%m%d"`
mkdir  ../history/dns/$date
cp -v test/* ../history/dns/$date
antal=0
for i in `cat ../domain` ; do
	echo $i
	nice dnscheck --policyfile /etc/dnscheck/policy.cron.yaml $i  >test/$i &
	 antal=$((antal+1))
	if [ $antal -eq 20 ]; then
                antal=0
                echo $antal
                sleep 90
	fi
done

sleep 180
	


