#!/bin/sh
cat /dev/null >errwww6
cat /dev/null >errdns6
cat /dev/null >errmx6

for i in `cat www6` ; do
	echo --- Testing www for $i
	wget -t 1 -T 3 -6 -o /dev/null  www.$i
	if [ $? != "0" ] ; then
		echo www.$i is not responding
		echo $i >> errwww6
	fi
	if [ -f index.html ] ; then	
		rm index.html
	fi
done

for i in `cat dns6` ; do
	echo --- Testing dns for $i
	for ns in `dig +short ns $i` ; do
                if [ "`host $ns | grep -i '[2-3][0-9|a-f][0-9|a-f][0-9|a-f]:'`" ] ; then
			echo testing dns $ns
			dig -6 +time=2 ns $i @$ns 2>&1 >/dev/null
			if [ $? != "0" ] ; then
			echo $ns is not responding 
				if [ ! `grep $i errdns6` ] ; then	
          		      		echo $i >> errdns6
        			fi
			fi
                fi
        done
		
done

for i in `cat mx6` ; do
	echo --- Testing mailserver for $i
        for mx in `dig +short mx $i` ; do
                if [ "`host $mx | grep -i '[2-3][0-9|a-f][0-9|a-f][0-9|a-f]:'`" ] ; then
			echo testing mailserver $mx
                       	echo quit|nc -6 -w 2 $mx 25 
                        if [ $? != "0" ] ; then
				echo $mx is not responding
				if [ ! `grep $i errmx6` ] ; then
                              		echo $i >> errmx6
				fi
                        fi
                fi
        done

done

date=`date +"%Y%m%d"`
cp errwww6 history/$date
cp errdns6 history/$date
cp errmx6  history/$date

