#!/bin/sh
digi=/home/dnssecandipv6/public_html/digi.html
cd /home/special/public_html/mipv6/script
echo "<h3>Myndigheter</h3>" >$digi
for i in `cat mx6` ; do
  if [ ! "`grep $i errmx6`" ] ; then
   if [ ! "`grep $i errwww6`" ] ; then
	if [ "`grep $i www6`" ] ; then
		if [ "`grep $i dns6`" ] ; then
			if [ "`dig +short ds $i`" ] ; then
				echo "<a href=www.$i>$i</a><br>" >>$digi
			fi	
		fi
	fi
    fi
  fi
done
cd /home/special/public_html/kipv6/script/
echo "<br><h3>Kommuner</h3>" >>$digi
for i in `cat mx6` ; do
  if [ ! "`grep $i errmx6`" ] ; then
   if [ ! "`grep $i errwww6`" ] ; then
	if [ "`grep $i www6`" ] ; then
		if [ "`grep $i dns6`" ] ; then
			if [ "`dig +short ds $i`" ] ; then
				echo "<a href=www.$i>$i</a><br>" >>$digi
			fi	
		fi
	fi
    fi
  fi
done
echo "<br>Sidan uppdaterades senast `date +"%Y-%m-%d %H:%M"`" >>$digi
