#!/bin/sh


for i in `cat domain|sort` ; do
        if [ "`cat test/$i| grep  "Enough valid signatures found for"`" != "" ] ; then
                dnssec=yes
        fi
	if [ "`cat test/$i| grep "is recursive"`" != "" ] ; then
		rec=yes
	fi
	ERROR=`cat test/$i|grep ERROR| wc -l`
	WARN=`cat test/$i|grep WARNING| wc -l`

	mail=`dig +time=3 +short soa $i|awk '{ print $2}'`
	dnser=`dig +time=3 +short ns $i`
	echo -n $i,$dnssec,$rec,$ERROR,$WARN,$mail,
	for dns in `echo $dnser` ; do
		echo -n $dns,
	done
	echo
	unset dnssec
	unset rec
done


