#!/bin/sh
cd /home/it-companies/public_html/rdns/script

antal=0
for i in `cat domain|sort` ; do
	echo $i
	dnscheck $i >test/$i &
	 antal=$((antal+1))
        if [ $antal -eq 20 ]; then
                antal=0
                echo $antal
                sleep 75
        fi
done

