#!/bin/sh

cd /home/special/bipv6

./checkipv6

cat mall.txt 
echo "<i>Updated `date`</i><br>"

echo "<h2>OMX30 med AAAA i deras www</h2>"
echo "<div class=\"subContainer\">"
echo "<b>`cat www6|wc -l ` of `cat domain|wc -l` domains<br></b>"
for i in `cat www6  `; do
 	echo "<div class="dom"><a href=\"http://www.$i\">$i</a></div>"
done
echo "<div style=\"break:both\">&nbsp;</div></div>"

echo "<h2><br>OMX30 med AAAA i sitt  MX RR</h2>"
echo "<div class=\"subContainer\">"
echo "<b>`cat mx6|wc -l ` of `cat domain|wc -l` domains<br></b>"
for i in `cat mx6  `; do
 	echo "<div class="dom"><a href=\"http://www.$i\">$i</a></div>"
done
echo "<div style="break:both">&nbsp;</div></div>"

echo "<br><h2>OXM30 med AAAA på någon DNS</h2>"
echo "<div class=\"subContainer\">"
echo "<b>`cat dns6|wc -l ` of `cat domain|wc -l` domains<br></b>"
for i in `cat dns6  `; do
 	echo "<div class=\"dom\"><a href=\"http://www.$i\">$i</a></div>"
done
echo "<div style=\"break:both\">&nbsp;</div></div>"


echo "<div style=\"break:both\">&nbsp;</div></div></p></div></body></html>"

