#!/bin/sh
cd /home/special/bipv6
rrdtool update ipv6.rrd N:`cat www6|wc -l`
cat www6|wc -l
rrdtool graph ipv6.png -w 800  --start end-365days --width 365 --lower-limit 0 --end now --slope-mode --vertical-label "Quad A www's" --title "Borsbolag quad A www"  DEF:www=ipv6.rrd:www:LAST LINE3:www#0000FF:""
cp ipv6.png ../public_html/bipv6


rrdtool update mx6.rrd N:`cat mx6|wc -l`
cat mx6|wc -l
rrdtool graph mx6.png -w 800  --start end-365days --width 365 --lower-limit 0 --end now --slope-mode --vertical-label "Quad A MX"  --title "Borsbolag quad A MX" DEF:www=mx6.rrd:mx6:LAST LINE3:www#0000FF:""
cp mx6.png ../public_html/bipv6


rrdtool update dns6.rrd N:`cat dns6|wc -l`
cat dns6|wc -l
rrdtool graph dns6.png -w 800  --start end-365days --width 365 --lower-limit 0 --end now --slope-mode --vertical-label "Quad A DNS" --title "Borsbolag quad A DNS" DEF:www=dns6.rrd:dns6:LAST LINE3:www#0000FF:""
cp dns6.png ../public_html/bipv6

