#!/bin/sh

cd /home/it-companies/public_html/slump2/ipv6/script

./checkipv6

cat mall.txt 
echo "<i>Updated `date`</i><br>"

echo "<h2>Slump with AAAA in their www name</h2>"
echo "<div class=\"subContainer\">"
echo "<b>`cat www6|wc -l ` of `cat domain|wc -l` domains<br></b>"
for i in `cat www6  `; do
 	echo "<div class="dom"><a href=\"http://www.$i\">$i</a></div>"
done
echo "<div style=\"break:both\">&nbsp;</div></div>"

echo "<h2><br>Slump with AAAA in its MX record</h2>"
echo "<div class=\"subContainer\">"
echo "<b>`cat mx6|wc -l ` of `cat domain|wc -l` domains<br></b>"
for i in `cat mx6  `; do
 	echo "<div class="dom"><a href=\"http://www.$i\">$i</a></div>"
done
echo "<div style="break:both">&nbsp;</div></div>"

echo "<br><h2>Slump with AAAA on some of their DNS servers</h2>"
echo "<div class=\"subContainer\">"
echo "<b>`cat dns6|wc -l ` of `cat domain|wc -l` domains<br></b>"
for i in `cat dns6  `; do
 	echo "<div class=\"dom\"><a href=\"http://www.$i\">$i</a></div>"
done
echo "<div style=\"break:both\">&nbsp;</div></div>"


echo "<div style=\"break:both\">&nbsp;</div></div></p></div></body></html>"

