#!/bin/sh


cd /home/newdnssec/kommunermeddnssec
cp secured secured.org

./dnssec2 |tee resultat.txt
php file.php < resultat.txt >../public_html/dns/index2.html
cp ../public_html/dns/index2.html ../public_html/dns/index.html

cat resultat.txt | awk -F , '{ print $1","$2}'|grep yes > secured
diff secured secured.org 
if [ "$?" = "1" ] ; then
	echo nya domäner!
	diff -y secured secured.org | egrep "<|>" | mail -s kommunermeddnssec tobbe@interlan.se
fi
./rrd
