#!/bin/sh
cd /home/kommunermeddnssec
mkdir versionhistory
date=`date +"%Y%m%d"`
mkdir versionhistory/$date
cp -v version/* versionhistory/$date


antal=0
for i in `cat kommun` ; do
        echo $i
        echo "----- $i -----"
        fpdns -t 1 -D $i | tee version/$i &
         antal=$((antal+1))
        if [ $antal -eq 20 ]; then
                antal=0
                echo $antal
                sleep 20
        fi


	echo
done

