#!/bin/sh
cd /home/newdnssec/kommunermeddnssec
rrdtool updatev dnssec.rrd N:`cat resultat.txt |cut -d , -f 2|grep yes|wc -l`
cat resultat.txt |cut -d , -f 2|grep yes|wc -l
rrdtool graph dnssec.png -w 800  --start end-365days --width 365 --end now --lower-limit 0 --slope-mode --vertical-label "Signed domains"  DEF:dnssec=dnssec.rrd:dnssec:LAST LINE3:dnssec#0000FF:""
cp dnssec.png ../public_html/dns/

