#!/bin/sh

/usr/local/bin/test sverige kommun dns
/usr/local/bin/test danmark kommun dns
/usr/local/bin/test norge kommun dns
/usr/local/bin/test finland kommun dns

/usr/local/bin/test sverige kommun ipv6
/usr/local/bin/test danmark kommun ipv6
/usr/local/bin/test norge kommun ipv6
/usr/local/bin/test finland kommun ipv6

/usr/local/bin/test sverige myndigheter ipv6
/usr/local/bin/test sverige myndigheter dns

php /usr/local/bin/importLogsDaily.php
php /usr/local/bin/importIpv6Daily.php
php /usr/local/bin/importDnssecDaily.php

