#!/bin/sh
country=$1
target=$2

source ./functions

case $target in
	kommun)
		htmldir=
		startdnssec kommun
		;;
	myndigheter)
		htmldir=
		startdnssec myndigheter
		;;
	landsting)
		htmldir=
		startdnssec landsting
		;;
esac
