#!/bin/sh

source ./functions
htmldir=$1
resultdir=./results
#cd /home/myndighetermeddnssec

case $target in
	kommun)
		htmldir=
		startdnssec kommun
		;;
	myndigheter)
		htmldir=
		startdnssec myndigheter
		;;
	landsting)
		htmldir=
		startdnssec landsting
		;;
esac
