#!/bin/sh
#cd /home/newdnssec/kommunermeddnssec
source ./functions

resultdir=../test
historydir=../history
date=`date +"%Y%m%d"`
mkdir "$resultdir"/$date
cp -v "$resultdir"/* "$historydir"/$date

case $target in
	kommun)
		resultdir=../test/kommun
		historydir=../history/kommun
		startdnscheck kommun
		;;
	myndigheter)
		resultdir=../test/myndigheter
		historydir=../history/myndigheter
		startdnscheck myndigheter
		;;
	landsting)
		resultdir=../test/landsting
		landstingdnscheck
		;;
esac
