#!/bin/sh
source ./functions

target=$1
resultdir=./results
historydir=../history
date=`date +"%Y%m%d"`

case $target in
	kommun)
		resultdir="$resultdir"/kommun
		historydir="$historydir"/kommun
		startdnscheck kommun
		;;
	myndigheter)
		resultdir="$resultdir"/myndigheter
		historydir="$historydir"/myndigheter
		startdnscheck myndigheter
		;;
	landsting)
		resultdir="$resultdir"/landsting
		landstingdnscheck
		;;
esac
