#!/bin/sh
country=$1
target=$2

source ./functions

echo $date

#getdnssecresult $date | tee $resultdir/$date.txt
getdnssecresult $target | tee $resultdir/$date.txt
#chown newdnssec.newdnssec  *

php transform.php $date $resultdir $historydir $country > public_html/data/$country/$date.json
#chown newdnssec.newdnssec  public_html/data/$date.json
