mkdir sverige
mkdir sverige/results
mkdir sverige/history
mkdir sverige/results/kommun
mkdir sverige/history/kommun
mkdir sverige/results/myndigheter
mkdir sverige/history/myndigheter
mkdir sverige/results/landsting
mkdir sverige/history/landsting
