#!/bin/sh
cd /home/dnssecandipv6/public_html/bankv6/scripts

rrdtool update ipv6.rrd N:`cat www6|wc -l`
cat www6|wc -l
rrdtool graph ipv6.png -w 800  --start end-365days --width 365 --lower-limit 0 --end now --slope-mode --vertical-label "Quad A www's"  DEF:ipv6=ipv6.rrd:ipv6:LAST LINE3:ipv6#0000FF:""
cp ipv6.png ..

rrdtool update mx6.rrd N:`cat mx6|wc -l`
cat mx6|wc -l
rrdtool graph mx6.png -w 800  --start end-365days --width 365 --lower-limit 0 --end now --slope-mode --vertical-label "Quad A MX"  DEF:www=mx6.rrd:mx6:LAST LINE3:www#0000FF:""
cp mx6.png ..

rrdtool update dns6.rrd N:`cat dns6|wc -l`
cat dns6|wc -l
rrdtool graph dns6.png -w 800  --start end-365days --width 365 --lower-limit 0 --end now --slope-mode --vertical-label "Quad A DNS"  DEF:www=dns6.rrd:dns6:LAST LINE3:www#0000FF:""
cp dns6.png ..

