#!/bin/sh
cat /dev/null > $1
for i in `cat resultat` ; do
	res=`echo $i | cut -d , -f 1`
	domain=`echo $i | cut -d , -f 2`
	if [ "$res" = "yes" ] ; then
		#echo "<a STYLE="color:green text-decoration:none" href=\"http://$domain\" \">$domain</a><br>" >> $1
		echo "<img width="16" height=14 src=/thumbsup.gif><span style="color:green"> $domain</span><br>" >> $1
	fi
 	if [ "$res" = "no" ] ; then

		#echo "<a STYLE="text-decoration:none color:red" href=\"http://$domain\" \">$domain</a><br>" >> $1
		echo "<img width="16" height=14 src=/nothumb.gif><span style="color:red"> $domain</span><br>" >> $1
        fi

done
echo "Updated `date`<br>">../public_html/worldipv6day/wipv62.html
echo "`cat resultat| cut -d , -f 1 | grep yes|wc -l` of 485 sites is IPv6 enabled<br><br>" >> ../public_html/worldipv6day/wipv62.html
#cat pic.html >> ../public_html/worldipv6day/wipv6.html


cat $1 >>../public_html/worldipv6day/wipv62.html

