#!/bin/sh
cd /home/it-companies/wipv6
res=`cat resultat |cut -d , -f 1|grep yes|wc -l`

rrdtool updatev ipv6.rrd N:$res
echo $res

rrdtool graph ipv6.png -w 800  --start end-4days --width 365 --lower-limit 0 --end now --slope-mode --vertical-label "IPv6 enabled sites"  DEF:ipv6=ipv6.rrd:ipv6:LAST LINE3:ipv6#0000FF:""
cp ipv6.png ../public_html/worldipv6day


