#!/bin/sh

date=$1
	cd /home/newdnssec
	echo $date
	
	cd data/resultat	

	sh dnssec2 $date | tee $date.txt
	chown newdnssec.newdnssec  *
	cd /home/newdnssec

	php transform.php $date > public_html/data/$date.json
	chown newdnssec.newdnssec  public_html/data/$date.json
