#!/bin/sh

	cd /home/newdnssec
	

#	for i in `seq 13` ; do

		date=$1
		cd data/resultat	
		sh dnssec2 $date | tee $date.txt
		chown newdnssec.newdnssec  *
		cd /home/newdnssec

		php transform.php $date > public_html/data/$date.json
		chown newdnssec.newdnssec  public_html/data/$date.json
#	done
