#!/bin/sh

cd /home/it-companies/public_html/kommits/scripts

./checkipv6

cat mall.txt 
echo "<i>Updated `date`</i><br>"

echo "<h2>Partners på Kommits 2010 med IPv6 på sin wwww</h2>"
echo "<div class=\"subContainer\">"
echo "<b>`cat www6|wc -l ` of `cat domain|wc -l` domains<br></b>"
for i in `cat www6  `; do
 	echo "<div class="dom"><a href=\"http://www.$i\">$i</a></div>"
done
echo "<div style=\"break:both\">&nbsp;</div></div>"

echo "<h2><br>Partners på Kommits 2010 med v6 på sin mail</h2>"
echo "<div class=\"subContainer\">"
echo "<b>`cat mx6|wc -l ` of `cat domain|wc -l` domains<br></b>"
for i in `cat mx6  `; do
 	echo "<div class="dom"><a href=\"http://www.$i\">$i</a></div>"
done
echo "<div style="break:both">&nbsp;</div></div>"

echo "<br><h2>Partnerts på Kommits 2010 med v6 på sin DNS</h2>"
echo "<div class=\"subContainer\">"
echo "<b>`cat dns6|wc -l ` of `cat domain|wc -l` domains<br></b>"
for i in `cat dns6  `; do
 	echo "<div class=\"dom\"><a href=\"http://www.$i\">$i</a></div>"
done
echo "<div style=\"break:both\">&nbsp;</div></div>"


echo "<div style=\"break:both\">&nbsp;</div></div></p></div></body></html>"

