#!/bin/sh
for i in $1 $2 $3 $4 $5 $6 $7 $8 $9 ${10} ${11} ${12} ${13} ${14} ${15}; do
        echo "----- $i -----"
	if [ "`cat domain|grep $i`" != "" ] ; then
		echo $i already exist
	fi
	if [ "`cat domain|grep $i`" = "" ] ; then
		dnscheck $i | tee test/$i
#        	fpdns -t 1 -D $i | tee version/$i
		echo $i >> domain
		cat domain| sort >>domain.temp
		mv domain.temp domain
		echo
	fi
done

./dnssec

