#!/bin/sh

dnsfile=dns6
mxfile=mx6
wwwfile=www6
cp $dnsfile ${dnsfile}.org
cp $mxfile ${mxfile}.org
cp $wwwfile ${wwwfile}.org

for i in $dnsfile $mxfile $wwwfile ; do
	cat /dev/null > $i
done

for i in `cat ../domain|sort | tr [A-Z] [a-z]` ; do
	echo $i 1>&2
	dnscheck=0
	mxcheck=0
	wwwcheck=0

	DNS=`dig +short ns $i`
	for ns in $DNS ; do
		if [ "`host $ns | grep -i '[2][0-9|a-z][0-9|a-z][0-9|a-z]:'`" ] && [ "$dnscheck" = "0" ] ; then
			echo $i >> $dnsfile
			dnscheck=1
		fi
	done
	MX=`dig +short mx $i|awk '{print $2}'`
        for mx in $MX ; do
                if [ "`host $mx | grep -i '[2][0-9|a-z][0-9|a-z][0-9|a-z]:'`"  ] && [ "$mxcheck" = "0" ]; then
			echo $i >> $mxfile
			mxcheck=1
                fi
        done
        if [ "`host www.$i | grep -i '[2][0-9|a-z][0-9|a-z][0-9|a-z]:'`"  ] ; then
			echo $i >> $wwwfile
			wwwcheck=1
        fi

done

for i in $dnsfile $mxfile $wwwfile ; do
	diff $i ${i}.org 2>&1 >/dev/null
	if [ "$?" = "1" ] ; then
		diff -y $i $i.org | grep ["<",">"]| mail -s companies-ipv6-$i tobbe@interlan.se
	fi
done

