#!/bin/sh
file=/tmp/$$
date=`date +"%Y%m%d"`


cd /home/special/public_html/kipv6/script

mkdir history/$date
#cp -v test/* history/$date

cp dns6 history/$date
cp mx6 history/$date
cp www6 history/$date


./ipv6 > $file
cat $file > ../index.html
rm $file

sh status

./rrd

