#!/bin/sh
cd /home/special/public_html/kipv6/script
rrdtool update ipv6.rrd N:`cat truewww6|wc -l`
cat truewww6|wc -l
rrdtool graph ipv6.png -w 800  --start end-365days --width 365 --lower-limit 0 --end now --slope-mode --vertical-label "Quad A www's" --title "Municipality quad A www"  DEF:www=ipv6.rrd:www:LAST LINE3:www#0000FF:""
cp ipv6.png ..

rrdtool update mx6.rrd N:`cat truemx6|wc -l`
cat truemx6|wc -l
rrdtool graph mx6.png -w 800  --start end-365days --width 365 --lower-limit 0 --end now --slope-mode --vertical-label "Quad A MX"  --title "Municipality quad A MX" DEF:www=mx6.rrd:mx6:LAST LINE3:www#0000FF:""
cp mx6.png ..

rrdtool update dns6.rrd N:`cat truedns6|wc -l`
cat truedns6|wc -l
rrdtool graph dns6.png -w 800  --start end-365days --width 365 --lower-limit 0 --end now --slope-mode --vertical-label "Quad A DNS" --title "Municipality quad A DNS" DEF:www=dns6.rrd:dns6:LAST LINE3:www#0000FF:""
cp dns6.png ..

