#!/bin/sh
cd /home/txv6tf 
./checkdns
./checkipv6




date=`date +"%Y%m%d"`

php transform.php $date > public_html/data/$date.json


chown -R txv6tf.txv6tf dns
chown -R txv6tf.txv6tf ipv6
chown -R txv6tf.txv6tf public_html
