#!/bin/sh
#date=`date +"%Y%m%d"`
date=$1

for i in `cat county` ; do
	i=`echo $i| cut -d , -f 1`	

	if [ "`cat dns/$date//$i| grep "Enough valid signatures over SOA RRset" | grep -v "Broken chain of trust" `" != "" ] ; then
		if [ "`cat dns/$date/$i| grep "Broken chain of trust" `" = "" ] ; then
			dnssec=yes
		fi
	fi
	if [ "`cat dns/$date/$i| grep "is recursive"`" != "" ] ; then
		rec=yes
	fi
	ERROR=`cat dns/$date/$i|grep ERROR| wc -l`
	WARN=`cat dns/$date/$i|grep WARNING| wc -l`

	mail=`dig +time=3 +short soa $i|awk '{ print $2}'`
	dnser=`dig +time=3 +short ns $i`
	echo -n $i,$dnssec,$rec,$ERROR,$WARN,$mail,
	for dns in `echo $dnser` ; do
		echo -n $dns,
	done
	echo
	unset dnssec
	unset rec
done


