#!/bin/sh

cd /home/dnssecandipv6
cp secured secured.org
./dnssec2 |tee resultat.txt
php file.php < resultat.txt >temp.html
mv temp.html public_html/dnssec/index.html

./rrd

cat resultat.txt | awk -F , '{ print $1","$2}'|grep yes > secured

diff secured secured.org 
if [ "$?" = "1" ] ; then
	echo nya domäner!
	diff -y secured secured.org | egrep "<|>" | mail -s dnssec-companies tobbe@interlan.se
fi

