#!/bin/sh
cd /home/dnssecandipv6
mkdir save/`date +"%Y%m%d"`
cp -v test/* save/`date +"%Y%m%d"`/
cp public_html/dnssec/index.html save/`date +"%Y%m%d"`/


for i in `cat domain` ; do
	echo $i
        dnscheck   $i  >test/$i &
         antal=$((antal+1))
        if [ $antal -eq 20 ]; then
                antal=0
                echo $antal
                sleep 75
        fi


done
