#!/bin/sh

./checkipv6
sh status 1>&2

cat mall.txt 
echo "<i>Updated `date`</i><br>"

echo "<h2>&Aringland Iland municipalities with AAAA in their www and domain name</h2>"
echo "<div class=\"subContainer\">"
echo "<b>`cat www6|wc -l ` of `cat domain|wc -l` domains<br></b>"
for i in `cat www6  `; do
   if [ ! "`cat errwww6| grep $i`" ] ; then
 	echo "<div class="dom"><a href=\"http://www.$i\">$i</a></div>"
   else
	echo "<div class="err">$i</div>"
   fi
done
echo "<div style=\"break:both\">&nbsp;</div></div>"

echo "<h2><br>&Aringland Iland municipalities with AAAA in its MX record</h2>"
echo "<div class=\"subContainer\">"
echo "<b>`cat mx6|wc -l ` of `cat domain|wc -l` domains<br></b>"
for i in `cat mx6  `; do
	if [ ! "`cat errmx6| grep $i`" ] ; then
 	    echo "<div class="dom"><a href=\"http://www.$i\">$i</a></div>"
	else
		echo "<div class="err">$i</div>"
        fi

done
echo "<div style="break:both">&nbsp;</div></div>"

echo "<div class=\"subContainer\">"
echo "<div><br><h2>&Aringland Iland municipalities with AAAA on some of their DNS servers</h2>"
echo "<div class=\"subContainer\">"
echo "<b>`cat dns6|wc -l ` of `cat domain|wc -l` domains<br></b>"
for i in `cat dns6  `; do
	if [ ! "`cat errdns6| grep $i`" ] ; then
	 	echo "<div class=\"dom\"><a href=\"http://www.$i\">$i</a></div>"
	else
		echo "<div class="err">$i</div>"
        fi


done
echo "<div style=\"break:both\">&nbsp;</div></div>"


echo "<div style=\"break:both\">&nbsp;</div></div></p></div></body></html>"

