#!/bin/sh

for j in 0 1 2 3 4 5 6 7 8 9 a b c d e f g h i j k l m n o p q r s t u v w x y z ; do

for i in `cat $j.txt` ; do
	dnscheck=0
	mxcheck=0
	wwwcheck=0

	DNS=`dig +short ns $i @$1`
	for ns in $DNS ; do
		if [ "`host $ns | grep -i '[2][0-9|a-z][0-9|a-z][0-9|a-z]:'`" ] && [ "$dnscheck" = "0" ] ; then
			dnscheck=1
		fi
	done
	MX=`dig +short mx $i @$1 |awk '{print $2}'`
        for mx in $MX ; do
                if [ "`host $mx | grep -i '[2][0-9|a-z][0-9|a-z][0-9|a-z]:'`"  ] && [ "$mxcheck" = "0" ]; then
			mxcheck=1
                fi
        done
        if [ "`host www.$i $1 | grep -i '[2][0-9|a-z][0-9|a-z][0-9|a-z]:'`"  ] ; then
			wwwcheck=1
        fi
			
	
	echo $i,$dnscheck,$mxcheck,$wwwcheck 



done

done
