#!/bin/sh
antal=0
cd /home/myndighetermeddnssec
for i in `cat domain` ; do
	echo $i
	nice dnscheck  --policyfile /etc/dnscheck/policy.cron.yaml $i  >test/$i &
	antal=$((antal+1))
	echo $antal
#	dnscheck $i  >test/$i &
	if [ $antal -eq 20 ]; then
                antal=0
                echo $antal
                sleep 180
	fi
done
for i in `cat domain` ; do
        echo $i
        echo $i | perl expire >> test/$i
#        sh ipv6dns $i
done
date=`date +"%Y%m%d"`
if [ ! -d history/$date ] ; then
	mkdir history/$date
fi
cp test/*  history/$date

sleep 180
