#!/bin/sh
cd /home/myndighetermeddnssec
antal=0
for i in `cat domain` ; do
		
	echo $i
	dnscheck $i  >test/$i &
	antal=$((antal+1))
	if [ $antal -eq 20 ]; then
		antal=0
		echo $antal
		sleep 120
	fi
done
