#!/usr/bin/perl -w

use Net::DNS;

while ( $domain = <STDIN> ) {
	chomp ($domain );

$res = new Net::DNS::Resolver;

$res->defnames(0);
$res->retry(2);
$ns_req = $res->query($domain, "NS");
if ( defined($ns_req) and ($ns_req->header->ancount > 0) ) {

  $soa_req = $res->send($domain, "SOA");
  unless (defined($soa_req)) {
      warn ": ", $res->errorstring, "\n";
      next;
  }
   unless (($soa_req->answer)[0]->type eq "SOA") {
       warn ": expected SOA, got ",
            ($soa_req->answer)[0]->type, "\n";
       next;
  }

  $expire=($soa_req->answer)[0]->expire;
  @parts=gmtime( ($soa_req->answer)[0]->expire );
	if ( $expire <= 86400 ) { 
			 printf "99.999 $domain WARNING SOA expire to low $expire seconds,%d days %d hours, \n",@parts[7,2];
	}

}


#  print "$domain ", ($soa_req->answer)[0]->expire, "\n";

}
